map SUPER+enter launch --cwd=current --type=os-window  
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66
confirm_os_window_close 0
scrollback_lines 1000
font_family JetBrainsMono
font_size 12.0

